services:
  result:
    networks:
      - backend
      - frontend
    container_name: result
    ports:
      - 5001:80
    image: result
  vote:
    networks:
      - backend
      - frontend
    container_name: vote
    ports:
      - 5000:80
    image: vote
  worker:
    networks:
      - backend
    container_name: worker
    image: worker
  postgres:
    networks:
      - backend
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql
    image: postgres
  redis:
    networks:
      - backend
    container_name: redis
    image: redis
networks:
  frontend:
    external: true
    name: frontend
  backend:
    external: true
    name: backend
volumes:
  db:
    external: true
    name: db
